name: Pull Request

on: pull_request

env:
  DOTNET_NOLOGO: true

jobs:

  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build version prefix/suffix
        run: |
          echo "VERSION_PREFIX=$(( 100 + ${{ github.run_number }} )).0.0" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=alpha" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:DebugType=Embedded -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - run: dotnet pack --configuration Release --no-build --output ./artifacts -p:DebugType=Embedded -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGetPackage.${{ env.VERSION_PREFIX }}-${{ env.VERSION_SUFFIX }}
          path: ./artifacts/
